"""add all core models

Revision ID: 479600030f49
Revises: 
Create Date: 2026-05-08 21:51:19.572951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '479600030f49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasons_id'), 'seasons', ['id'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tournament_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('buy_in', sa.Integer(), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('current_players', sa.Integer(), nullable=True),
    sa.Column('is_bounty', sa.Boolean(), nullable=True),
    sa.Column('is_highroller', sa.Boolean(), nullable=True),
    sa.Column('double_points', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_id'), 'tournaments', ['id'], unique=False)
    op.create_table('blind_timers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('small_blind', sa.Integer(), nullable=False),
    sa.Column('big_blind', sa.Integer(), nullable=False),
    sa.Column('ante', sa.Integer(), nullable=True),
    sa.Column('level_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('seconds_remaining', sa.Integer(), nullable=False),
    sa.Column('is_running', sa.Boolean(), nullable=True),
    sa.Column('total_chips', sa.Integer(), nullable=True),
    sa.Column('players_remaining', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id')
    )
    op.create_index(op.f('ix_blind_timers_id'), 'blind_timers', ['id'], unique=False)
    op.create_table('eliminations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('eliminated_user_id', sa.Integer(), nullable=False),
    sa.Column('eliminated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('finish_position', sa.Integer(), nullable=False),
    sa.Column('players_remaining', sa.Integer(), nullable=False),
    sa.Column('eliminated_at', sa.DateTime(), nullable=True),
    sa.Column('recorded_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['eliminated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['eliminated_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eliminations_id'), 'eliminations', ['id'], unique=False)
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friendships_id'), 'friendships', ['id'], unique=False)
    op.create_table('maskcoin_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maskcoin_transactions_id'), 'maskcoin_transactions', ['id'], unique=False)
    op.create_table('tournament_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('seat_number', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_registrations_id'), 'tournament_registrations', ['id'], unique=False)
    op.create_table('tournament_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('final_position', sa.Integer(), nullable=False),
    sa.Column('total_players', sa.Integer(), nullable=False),
    sa.Column('knockouts', sa.Integer(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_results_id'), 'tournament_results', ['id'], unique=False)
    op.add_column('users', sa.Column('poker_nickname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('maskcoin_balance', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('referral_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('referred_by_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'telegram_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['referral_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'referred_by_id')
    op.drop_column('users', 'referral_code')
    op.drop_column('users', 'maskcoin_balance')
    op.drop_column('users', 'poker_nickname')
    op.drop_index(op.f('ix_tournament_results_id'), table_name='tournament_results')
    op.drop_table('tournament_results')
    op.drop_index(op.f('ix_tournament_registrations_id'), table_name='tournament_registrations')
    op.drop_table('tournament_registrations')
    op.drop_index(op.f('ix_maskcoin_transactions_id'), table_name='maskcoin_transactions')
    op.drop_table('maskcoin_transactions')
    op.drop_index(op.f('ix_friendships_id'), table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_eliminations_id'), table_name='eliminations')
    op.drop_table('eliminations')
    op.drop_index(op.f('ix_blind_timers_id'), table_name='blind_timers')
    op.drop_table('blind_timers')
    op.drop_index(op.f('ix_tournaments_id'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_seasons_id'), table_name='seasons')
    op.drop_table('seasons')
    # ### end Alembic commands ###
